# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # m38 Base Vagrant image
  config.vm.box = 'm38io/ubuntu-14-04-x64'

  # Check for box updates
  config.vm.box_check_update = true

  # Configure host-only network
  config.vm.network 'private_network', ip: '192.168.76.10'
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 1773, host: 1773
  config.vm.network "forwarded_port", guest: 3308, host: 3308

  # Share folder, disabled sync by default due to issues on windows with SMB
  # sharing. You can enable sync by setting the VAGRANT_SYNC_ENABLED env var
  # to true.
  sync_disabled = true
  if ENV['VAGRANT_SYNC_ENABLED']
    sync_disabled = !ENV['VAGRANT_SYNC_ENABLED']
  end
  config.vm.synced_folder './', '/home/vagrant/is4', disabled: sync_disabled

  # Configure the virtual machine to use 2GB of RAM
  config.vm.provider :virtualbox do |vb|
    vb.name = "is4"
    vb.customize [
                     'modifyvm', :id,
                     '--memory', '1024',
                     '--cpus', '1'
                 ]
  end
end
